#!/bin/sh

ls -l ら・ら・ら_なかむランド/*.flv | wc -l; 
ls -l りめいく！/*.flv | wc -l; 
ls -l れいandゆいの文化放送ホームランラジオ！/*.flv | wc -l; 
ls -l アニアモ/*.flv | wc -l; 
ls -l セガネットワークスアワー_村川梨衣・大坪由佳のムラツボ研究所/*.flv | wc -l; 
ls -l セハガールのハードなSEGA情報RADIO「セハラジ」/*.flv | wc -l; 
ls -l メゾン_ド_イーコエ_もしも声優がいっぱい住んでいるマンションがあったら_Pyxisの夜空の下_de_Meeting/*.flv | wc -l; 
ls -l メゾン_ド_イーコエ_もしも声優がいっぱい住んでいるマンションがあったら_高野麻里佳_あなたの隣家のまりんか/*.flv | wc -l;
ls -l ラジオどっとあい_夏川椎菜のナンスの角に小指ぶつけて痛い/*.flv | wc -l;
ls -l ラジオどっとあい_本渡楓のめいっぷるんっ！/*.flv | wc -l;
ls -l ラジオどっとあい_花守ゆみりのいろんなゆみりをみてゆみり/*.flv | wc -l;
ls -l ラジオどっとあい_麻倉もものもちょやまばなし/*.flv | wc -l;
ls -l 三上枝織のAandG_NEXT_GENERATION_Lady_Go！！/*.flv | wc -l;
ls -l 三上枝織の「みかっしょ！」/*.flv | wc -l;
ls -l 上坂すみれの_AandG_NEXT_GENERATION_Lady_Go！！/*.flv | wc -l;
ls -l 久保ユリカが1人しゃべりなんて胃が痛い。/*.flv | wc -l;
ls -l 井上麻里奈下田麻美のIT革命！/*.flv | wc -l;
ls -l 井口裕香のむーーーん/*.flv | wc -l;
ls -l 伊藤美来_まるっとまとめ！/*.flv | wc -l;
ls -l 佳村はるかのひみつきち/*.flv | wc -l;
ls -l 内田さんと浅倉さん/*.flv | wc -l;
ls -l 内田真礼とおはなししません？/*.flv | wc -l;
ls -l 南條愛乃_エオルゼアより愛をこめて/*.flv | wc -l;
echo " "; 
ls -l ../mp4/conv/ら・ら・ら_なかむランド/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/りめいく！/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/れいandゆいの文化放送ホームランラジオ！/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/アニアモ/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/セガネットワークスアワー_村川梨衣・大坪由佳のムラツボ研究所/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/セハガールのハードなSEGA情報RADIO「セハラジ」/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/メゾン_ド_イーコエ_もしも声優がいっぱい住んでいるマンションがあったら_Pyxisの夜空の下_de_Meeting/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/メゾン_ド_イーコエ_もしも声優がいっぱい住んでいるマンションがあったら_高野麻里佳_あなたの隣家のまりんか/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/ラジオどっとあい_夏川椎菜のナンスの角に小指ぶつけて痛い/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/ラジオどっとあい_本渡楓のめいっぷるんっ！/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/ラジオどっとあい_花守ゆみりのいろんなゆみりをみてゆみり/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/ラジオどっとあい_麻倉もものもちょやまばなし/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/三上枝織のAandG_NEXT_GENERATION_Lady_Go！！/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/三上枝織の「みかっしょ！」/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/上坂すみれの_AandG_NEXT_GENERATION_Lady_Go！！/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/久保ユリカが1人しゃべりなんて胃が痛い。/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/井上麻里奈下田麻美のIT革命！/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/井口裕香のむーーーん/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/伊藤美来_まるっとまとめ！/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/佳村はるかのひみつきち/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/内田さんと浅倉さん/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/内田真礼とおはなししません？/*.mp4 2> /dev/null | wc -l;
ls -l ../mp4/conv/南條愛乃_エオルゼアより愛をこめて/*.mp4 2> /dev/null | wc -l;